# LEFT DRIVER
LEFT_RPWM = 13
LEFT_LPWM = 12
LEFT_REN  = 5
LEFT_LEN  = 6

# RIGHT DRIVER
RIGHT_RPWM = 18
RIGHT_LPWM = 19
RIGHT_REN  = 20
RIGHT_LEN  = 21

PWM_FREQ = 1000
DEFAULT_SPEED = 0.6

STOP_MM = 400
SLOW_MM = 800

# Tracking Configuration
TARGET_NAME = 'Carl'
FRAME_CENTER_X = 208  # Updated for 416 width
DEVIATION_THRESH = 50
GRID_COLS = 8
OBSTACLE_COL = 4
